name: risuai-latest

services:
  risuai-latest:
    container_name: risuai-latest
    build: .
    restart: always
    environment:
      - PORT=6001 
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "6002:6001" # 외부 6002를 컨테이너 내부 6001로 연결
    volumes:
      - /volume2/docker/risu-latest:/app/save # 절대 경로를 직접 매핑
